// @title           E-Wallet System API
// @version         1.0
// @description     Simplified multi-currency e-wallet backend — core ledger for a fintech app.
// @host            localhost:8080
// @BasePath        /

// Command server is the entry point for the e-wallet HTTP server.
// It wires together the database connection, schema migrations, wallet
// service, and Echo HTTP server, then runs until a shutdown signal
// (SIGINT or SIGTERM) is received.
//
// Configuration is read from environment variables with sensible
// defaults so the binary works out of the box with the docker-compose
// setup. See .env.example for the full list.
package main

import (
	"context"
	"errors"
	"log"
	"net/http"
	"os"
	"os/signal"
	"path/filepath"
	"reflect"
	"runtime"
	"strings"
	"syscall"
	"time"

	"github.com/go-playground/validator/v10"
	"github.com/joho/godotenv"
	"github.com/labstack/echo/v4"
	"github.com/labstack/echo/v4/middleware"
	echoSwagger "github.com/swaggo/echo-swagger"

	"github.com/AdityaIrfan/e-wallet-system-vocagame/db"
	_ "github.com/AdityaIrfan/e-wallet-system-vocagame/docs" // swag-generated Swagger spec
	"github.com/AdityaIrfan/e-wallet-system-vocagame/handler"
	pgstore "github.com/AdityaIrfan/e-wallet-system-vocagame/storage/postgres"
	"github.com/AdityaIrfan/e-wallet-system-vocagame/wallet"
)

func main() {
	envPath := loadEnv()
	if err := godotenv.Load(envPath); err != nil {
		log.Println("Notice: File .env tidak ditemukan, menggunakan environment sistem/fallback")
	}

	dsn := getEnv("DATABASE_URL", "postgres://ewallet:ewallet@localhost:5432/ewallet?sslmode=disable")
	migrationsPath := getEnv("MIGRATIONS_PATH", "file://migrations")
	port := getEnv("PORT", "8080")

	// ── database ──────────────────────────────────────────────────────
	database, err := db.Connect(dsn)
	if err != nil {
		log.Fatalf("connect to database: %v", err)
	}
	defer database.Close()

	// Apply any pending migrations before accepting traffic. ErrNoChange
	// (schema already up to date) is treated as success inside db.Migrate.
	if err := db.Migrate(dsn, migrationsPath); err != nil {
		log.Fatalf("run migrations: %v", err)
	}
	log.Println("migrations applied")

	// ── service ───────────────────────────────────────────────────────
	// NewService takes the four storage dependencies separately so the
	// wallet package never imports anything Postgres-specific.
	svc := wallet.NewService(
		pgstore.NewWalletRepo(database),
		pgstore.NewLedgerRepo(database),
		pgstore.NewOwnerRepo(database),
		pgstore.NewUnitOfWork(database),
	)

	// ── echo ──────────────────────────────────────────────────────────
	e := echo.New()
	e.HideBanner = true

	v := validator.New()
	v.RegisterTagNameFunc(func(fld reflect.StructField) string {
		name := strings.SplitN(fld.Tag.Get("json"), ",", 2)[0]
		if name == "-" {
			return ""
		}
		return name
	})

	e.Validator = &customValidator{v}

	e.Use(middleware.RequestLogger()) // structured request logging
	e.Use(middleware.Recover())       // recover from panics, return 500
	e.Use(middleware.RequestID())     // attach a unique ID to every request

	// Swagger UI is available at /swagger/index.html.
	// Docs are generated by `swag init` and embedded via the docs import.
	e.GET("/swagger/*", echoSwagger.WrapHandlerV3)

	handler.New(svc).Register(e)

	// ── graceful shutdown ─────────────────────────────────────────────
	// Start serving in a goroutine so the main goroutine can block on
	// the signal channel. On shutdown, give in-flight requests up to
	// 10 seconds to complete before forcing a close.
	go func() {
		if err := e.Start(":" + port); err != nil && !errors.Is(err, http.ErrServerClosed) {
			log.Fatalf("server error: %v", err)
		}
	}()
	log.Printf("server started on :%s — docs at http://localhost:%s/swagger/index.html", port, port)

	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	<-quit
	log.Println("shutting down...")

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	if err := e.Shutdown(ctx); err != nil {
		log.Printf("shutdown error: %v", err)
	}
	log.Println("server stopped")
}

func loadEnv() string {
	_, currentFile, _, _ := runtime.Caller(0)
	projectRoot := filepath.Join(filepath.Dir(currentFile), "../..") // Sesuaikan tingkat folder
	envPath := filepath.Join(projectRoot, ".env")
	return envPath
}

// getEnv returns the value of the environment variable named key, or
// fallback if the variable is unset or empty.
func getEnv(key, fallback string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return fallback
}

// customValidator bridges go-playground/validator to Echo's Validator
// interface. Struct tags like `validate:"required"` are checked via
// this validator before any handler body runs — handlers can assume
// validated fields are non-empty.
type customValidator struct {
	v *validator.Validate
}

func (cv *customValidator) Validate(i interface{}) error {
	return cv.v.Struct(i)
}
